### ISSUE TITLE
Add `show users`, `show orgs` and `show teams` commands.

### ISSUE THREAD

**Issue by downie** [usermindinc/hubot-github-pr-reporter#10]
This is from feedback that it's currently hard to know what values to put for the various `user:`, `team:` and `org:` filtering options.

Add 3 commands to this hubot plugin:
1. `show orgs` will show all organizations that HUBOT_GITHUB_USER is a member of.
2. `show teams` will show available team names, grouped by organization.
3. `show users` will list all users HUBOT_GITHUB_USER can see across all organizations.

**Comment by bfosberry** [comment]
:+1:

**Comment by downie** [comment]
1.1.5 has been released, which has this feature added to it.
