### ISSUE TITLE
Having issues with the cron functionality.

### ISSUE THREAD

**Issue by bfosberry** [usermindinc/hubot-github-pr-reporter#11]
Hey, thanks for all the help so far. We're hosting hubot on heroku, and we're not seeing any cron functionality working. Is there anything we need to do to get this running? I have a subscription to all prs weekdays at noon. Should that be coming in hubots timezone, my timezone, or the system timezone on heroku? I see no errors in the logs from it trying to send a notification.

thanks
Brendan

**Comment by downie** [comment]
What's an example command you're sending hubot? 

It runs the value of the cron string on the server clock. So if your server is set to UTC, by default it'll fire weekdays at noon UTC.

**Comment by bfosberry** [comment]
That makes sense.

```
bfosberry [10:00 AM] 
subscribe prs

captainBOT [10:00 AM] 
bfosberry: Great! This request will show you all PRs at the default frequency (weekdays at noon)
```

Then I get no messages, or any logs indicating its running in heroku. There are plenty of prs though :P.

I suspect we just need to hook hubot up in heroku to run a cron task

**Comment by downie** [comment]
Hm. That's surprising. Even if there are no PRs, it should say so at the cron frequency. Something should show up like this:
```
Nothing found for all PRs in the <TEAM> team in the <ORG> organization
To unsubscribe, type `hubot unsubscribe prs 10`
```
We use [node-schedule](https://github.com/node-schedule/node-schedule) for scheduling the cron jobs. maybe there's something wrong with that dependency in your environment?

As a test, you could ask it to fire off every minute: 
```
hubot subscribe prs cron:”0 * * * * *"
```

**Comment by bfosberry** [comment]
how weird! that works! There must be something wrong with the default schedule. thanks for the tip! I'll set up a daily non-standard schedule and that should work for me

**Comment by bfosberry** [comment]
Oh I just noticed this: 

```
15    bfosberry    paused => all orgs
```

that was my default schedule one

**Comment by downie** [comment]
ah! of course. I should have remembered. It's a quirk of hubot plugins that I'd love to code my way around, if possible:

Currently, when hubot sees a `subscribe` command, it captures the requesting room in a closure, and sends that closure to that `node-schedule` module to run it. If the server ever restarts, that closure is lost. While hubot remembers that it's supposed to post to a room at a certain time, without the room object itself, it can't just post without it being a response to something.

Hence, [this little hack](https://github.com/usermindinc/hubot-github-pr-reporter/blob/master/src/github-pr-reporter.coffee#L479-L486). Whenever it hears *anything* in a room, it checks its list to see if there's anything scheduled to be posted to that room. Until it does, it's listed in that "paused" state that you're seeing.

If you can figure out a means of removing this quirk, I'd greatly appreciate it. My previous attempts at storing it in the brain with the rest of the request details didn't pan out.
