### ISSUE TITLE
Please document required github token scopes

### ISSUE THREAD

**Issue by bfosberry** [usermindinc/hubot-github-pr-reporter#7]
Currently it's trial and error figuring out what scopes are needed

**Comment by downie** [comment]
What do you mean by "token scopes"? Do you mean the values for the `HUBOT_GITHUB_TOKEN` and `HUBOT_GITHUB_USER` variables?

**Comment by bfosberry** [comment]
Nah, the github access github scopes, I.e. org:read

**Comment by downie** [comment]
Gotcha. I'll add some more notes to the README to make that more clear.

**Comment by downie** [comment]
I added a few more lines to the README to explain where to find appropriate values for the different filters.

I also created #10 so you could interactively query hubot for acceptable values. I'll get to it, but probably not for another month or two. If you're up to it, I'd gladly accept a PR for it. :)

**Comment by bfosberry** [comment]
thanks!
